
import { DraftPick, TradeType } from "../types";

// Helper to create simple own pick
const own = (year: number, team: string, player: string, round: 1 | 2 = 1): DraftPick => ({
    year, round, originalOwnerId: team, status: TradeType.OWN, details: player, player
});

// Helper to create traded pick
const traded = (year: number, original: string, current: string, player: string, details: string = "Traded", round: 1 | 2 = 1): DraftPick => ({
    year, round, originalOwnerId: original, currentOwnerId: current, status: TradeType.TRADED, details: `${player} (${details})`, player
});

export const PAST_DRAFTS_DATA: DraftPick[] = [
    // --- 2025 Round 1 ---
    own(2025, 'DAL', 'Cooper Flagg', 1),
    own(2025, 'SAS', 'Dylan Harper', 1),
    own(2025, 'PHI', 'V. J. Edgecombe', 1),
    own(2025, 'CHA', 'Kon Knueppel', 1),
    own(2025, 'UTA', 'Ace Bailey', 1),
    own(2025, 'WAS', 'Tre Johnson', 1),
    own(2025, 'NOP', 'Jeremiah Fears', 1),
    own(2025, 'BKN', 'Egor Demin', 1),
    own(2025, 'TOR', 'Collin Murray-Boyles', 1),
    traded(2025, 'HOU', 'PHX', 'Khaman Maluach', 'via BKN', 1),
    traded(2025, 'POR', 'MEM', 'Cedric Coward', 'Traded to MEM', 1),
    own(2025, 'CHI', 'Noa Essengue', 1),
    traded(2025, 'ATL', 'NOP', 'Derik Queen', 'via SAC', 1),
    traded(2025, 'SAS', 'SAS', 'Carter Bryant', 'from ATL', 1),
    traded(2025, 'OKC', 'OKC', 'Thomas Sorber', 'from MIA via LAC', 1),
    traded(2025, 'MEM', 'POR', 'Yang Hansen', 'from ORL', 1),
    traded(2025, 'MIN', 'MIN', 'Joan Beringer', 'from DET via NYK/OKC/HOU', 1),
    traded(2025, 'WAS', 'WAS', 'Walter Clayton Jr.', 'from MEM', 1),
    traded(2025, 'BKN', 'BKN', 'Nolan Traoré', 'from MIL via NYK/DET/POR/NOP', 1),
    traded(2025, 'MIA', 'MIA', 'Kasparas Jakučionis', 'from GSW', 1),
    traded(2025, 'UTA', 'UTA', 'Will Riley', 'from MIN', 1),
    traded(2025, 'ATL', 'BKN', 'Drake Powell', 'from LAL via NOP', 1),
    traded(2025, 'NOP', 'ATL', 'Asa Newell', 'from IND', 1),
    traded(2025, 'OKC', 'SAC', 'Nique Clifford', 'from LAC', 1),
    traded(2025, 'ORL', 'ORL', 'Jase Richardson', 'from DEN', 1),
    traded(2025, 'BKN', 'BKN', 'Ben Saraf', 'from NYK', 1),
    traded(2025, 'BKN', 'BKN', 'Danny Wolf', 'from HOU', 1),
    own(2025, 'BOS', 'Hugo González', 1),
    traded(2025, 'PHX', 'CHA', 'Liam McNeeley', 'from CLE via UTA', 1),
    traded(2025, 'LAC', 'LAC', 'Yanic Konan Niederhäuser', 'from OKC', 1),

    // --- 2025 Round 2 ---
    traded(2025, 'MIN', 'PHX', 'Rasheer Fleming', 'from UTA', 2),
    traded(2025, 'BOS', 'ORL', 'Noah Penda', 'from WAS via DET/BKN', 2),
    own(2025, 'CHA', 'Sion James', 2),
    traded(2025, 'CHA', 'CHA', 'Ryan Kalkbrenner', 'from NOP via SAS/PHX/MEM', 2),
    own(2025, 'PHI', 'Johni Broome', 2),
    traded(2025, 'BKN', 'LAL', 'Adou Thiero', 'Traded to LAL', 2),
    traded(2025, 'DET', 'DET', 'Chaz Lanier', 'from TOR via DAL/SAS', 2),
    traded(2025, 'SAS', 'IND', 'Kam Jones', 'Traded to IND', 2),
    traded(2025, 'TOR', 'TOR', 'Alijah Martin', 'from POR via SAC', 2),
    traded(2025, 'WAS', 'IND', 'Micah Peavy', 'from PHX', 2),
    traded(2025, 'GSW', 'PHX', 'Koby Brea', 'from MIA via BKN/IND', 2),
    traded(2025, 'SAC', 'SAC', 'Maxime Raynaud', 'from CHI via SAS', 2),
    traded(2025, 'UTA', 'UTA', 'Jamir Watkins', 'from DAL', 2),
    traded(2025, 'OKC', 'OKC', 'Brooks Barnhizer', 'from ATL', 2),
    traded(2025, 'CHI', 'MIN', 'Rocco Zikarsky', 'from SAC via LAL', 2),
    traded(2025, 'ORL', 'BOS', 'Amari Williams', 'Traded to BOS', 2),
    traded(2025, 'MIL', 'MIL', 'Bogoljub Marković', 'from DET via WAS', 2),
    traded(2025, 'MEM', 'MEM', 'Javon Small', 'from GSW via WAS/BKN', 2),
    traded(2025, 'CLE', 'CLE', 'Tyrese Proctor', 'from MIL', 2),
    traded(2025, 'NYK', 'LAC', 'Kobe Sanders', 'from MEM via OKC/BOS', 2),
    traded(2025, 'LAC', 'NYK', 'Mohamed Diawara', 'from MIN via ATL/HOU', 2),
    traded(2025, 'PHX', 'GSW', 'Alex Toohey', 'from DEN via CHA/MIN', 2),
    traded(2025, 'UTA', 'UTA', 'John Tonje', 'from LAC via LAL', 2),
    own(2025, 'IND', 'Taelon Peter', 2),
    traded(2025, 'LAL', 'CHI', 'Lachlan Olbrich', 'Traded to CHI', 2),
    traded(2025, 'MEM', 'GSW', 'Will Richard', 'from HOU', 2),
    traded(2025, 'ORL', 'BOS', 'Max Shulga', 'from BOS', 2),
    own(2025, 'CLE', 'Saliou Niang', 2),
    traded(2025, 'HOU', 'MEM', 'Jahmai Mashack', 'from OKC via ATL/GSW', 2),

    // --- 2024 Round 1 ---
    own(2024, 'ATL', 'Zaccharie Risacher', 1),
    own(2024, 'WAS', 'Alex Sarr', 1),
    traded(2024, 'HOU', 'HOU', 'Reed Sheppard', 'from BKN', 1),
    own(2024, 'SAS', 'Stephon Castle', 1),
    own(2024, 'DET', 'Ron Holland', 1),
    own(2024, 'CHA', 'Tidjane Salaün', 1),
    own(2024, 'POR', 'Donovan Clingan', 1),
    traded(2024, 'SAS', 'MIN', 'Rob Dillingham', 'from TOR', 1),
    own(2024, 'MEM', 'Zach Edey', 1),
    own(2024, 'UTA', 'Cody Williams', 1),
    own(2024, 'CHI', 'Matas Buzelis', 1),
    traded(2024, 'OKC', 'OKC', 'Nikola Topić', 'from HOU', 1),
    own(2024, 'SAC', 'Devin Carter', 1),
    traded(2024, 'POR', 'WAS', 'Bub Carrington', 'from GSW via MEM/BOS', 1),
    own(2024, 'MIA', 'Kel\'el Ware', 1),
    own(2024, 'PHI', 'Jared McCain', 1),
    own(2024, 'LAL', 'Dalton Knecht', 1),
    own(2024, 'ORL', 'Tristan da Silva', 1),
    traded(2024, 'TOR', 'TOR', 'Ja\'Kobe Walter', 'from IND', 1),
    own(2024, 'CLE', 'Jaylon Tyson', 1),
    traded(2024, 'NOP', 'NOP', 'Yves Missi', 'from MIL', 1),
    traded(2024, 'PHX', 'DEN', 'DaRon Holmes II', 'Traded to DEN', 1),
    traded(2024, 'MIL', 'MIL', 'AJ Johnson', 'from NOP', 1),
    traded(2024, 'NYK', 'WAS', 'Kyshawn George', 'from DAL', 1),
    own(2024, 'NYK', 'Pacôme Dadiet', 1),
    traded(2024, 'WAS', 'OKC', 'Dillon Jones', 'from LAC/OKC/DAL', 1),
    own(2024, 'MIN', 'Terrence Shannon Jr.', 1),
    traded(2024, 'DEN', 'PHX', 'Ryan Dunn', 'Traded to PHX', 1),
    traded(2024, 'UTA', 'UTA', 'Isaiah Collier', 'from OKC/IND/TOR', 1),
    own(2024, 'BOS', 'Baylor Scheierman', 1),

    // --- 2024 Round 2 ---
    traded(2024, 'TOR', 'TOR', 'Jonathan Mogbo', 'from DET/LAC/NYK', 2),
    traded(2024, 'UTA', 'UTA', 'Kyle Filipowski', 'from WAS/BKN/DET', 2),
    traded(2024, 'MIL', 'MIL', 'Tyler Smith', 'from POR/SAC', 2),
    traded(2024, 'POR', 'NYK', 'Tyler Kolek', 'from CHA/NOP/OKC/DEN', 2),
    traded(2024, 'SAS', 'IND', 'Johnny Furphy', 'Traded to IND', 2),
    traded(2024, 'IND', 'SAS', 'Juan Núñez', 'from TOR/MEM/LAC/PHI', 2),
    traded(2024, 'MIN', 'DET', 'Bobi Klintman', 'from MEM/OKC/WAS/LAL', 2),
    traded(2024, 'NYK', 'OKC', 'Ajay Mitchell', 'from UTA', 2),
    traded(2024, 'MEM', 'MEM', 'Jaylen Wells', 'from BKN/HOU', 2),
    traded(2024, 'POR', 'PHX', 'Oso Ighodaro', 'from ATL', 2),
    traded(2024, 'PHI', 'PHI', 'Adem Bona', 'from CHI/NOP/SAS/BOS', 2),
    traded(2024, 'CHA', 'CHA', 'KJ Simpson', 'from HOU/OKC', 2),
    traded(2024, 'MIA', 'ATL', 'Nikola Đurišić', 'Traded to ATL', 2),
    traded(2024, 'HOU', 'MIA', 'Pelle Larsson', 'from GSW/ATL', 2),
    traded(2024, 'SAC', 'TOR', 'Jamal Shead', 'Traded to TOR', 2),
    traded(2024, 'LAC', 'LAC', 'Cam Christie', 'from IND/MIL/MEM', 2),
    traded(2024, 'ORL', 'NOP', 'Antonio Reeves', 'Traded to NOP', 2),
    traded(2024, 'SAS', 'SAS', 'Harrison Ingram', 'from LAL/MEM', 2),
    traded(2024, 'IND', 'IND', 'Tristen Newton', 'from CLE', 2),
    traded(2024, 'IND', 'IND', 'Enrique Freeman', 'from NOP', 2),
    traded(2024, 'NYK', 'DAL', 'Melvin Ajinça', 'from PHX/WAS', 2),
    traded(2024, 'GSW', 'GSW', 'Quinten Post', 'from MIL/IND', 2),
    traded(2024, 'DET', 'MEM', 'Cam Spencer', 'from NYK/CHA/PHI', 2),
    traded(2024, 'BOS', 'BOS', 'Anton Watson', 'from DAL/SAC', 2),
    traded(2024, 'LAL', 'LAL', 'Bronny James', 'from LAC', 2),
    traded(2024, 'DEN', 'NYK', 'Kevin McCullar Jr.', 'from MIN/OKC', 2),
    traded(2024, 'MEM', 'TOR', 'Ulrich Chomche', 'from OKC/ATL/HOU', 2),
    traded(2024, 'DAL', 'NYK', 'Ariel Hukporti', 'from BOS/CHA', 2),

    // --- 2023 Round 1 ---
    own(2023, 'SAS', 'Victor Wembanyama', 1),
    own(2023, 'CHA', 'Brandon Miller', 1),
    own(2023, 'POR', 'Scoot Henderson', 1),
    own(2023, 'HOU', 'Amen Thompson', 1),
    own(2023, 'DET', 'Ausar Thompson', 1),
    own(2023, 'ORL', 'Anthony Black', 1),
    traded(2023, 'IND', 'WAS', 'Bilal Coulibaly', 'Traded to WAS', 1),
    traded(2023, 'WAS', 'IND', 'Jarace Walker', 'Traded to IND', 1),
    own(2023, 'UTA', 'Taylor Hendricks', 1),
    traded(2023, 'DAL', 'OKC', 'Cason Wallace', 'Traded to OKC', 1),
    traded(2023, 'ORL', 'ORL', 'Jett Howard', 'from CHI', 1),
    traded(2023, 'OKC', 'DAL', 'Dereck Lively II', 'Traded to DAL', 1),
    own(2023, 'TOR', 'Gradey Dick', 1),
    own(2023, 'NOP', 'Jordan Hawkins', 1),
    own(2023, 'ATL', 'Kobe Bufkin', 1),
    traded(2023, 'UTA', 'UTA', 'Keyonte George', 'from MIN', 1),
    own(2023, 'LAL', 'Jalen Hood-Schifino', 1),
    own(2023, 'MIA', 'Jaime Jaquez Jr.', 1),
    own(2023, 'GSW', 'Brandin Podziemski', 1),
    traded(2023, 'HOU', 'HOU', 'Cam Whitmore', 'from LAC', 1),
    traded(2023, 'BKN', 'BKN', 'Noah Clowney', 'from PHX', 1),
    own(2023, 'BKN', 'Dariq Whitehead', 1),
    traded(2023, 'POR', 'POR', 'Kris Murray', 'from NYK', 1),
    traded(2023, 'SAC', 'DAL', 'Olivier-Maxence Prosper', 'Traded to DAL', 1),
    traded(2023, 'MEM', 'DET', 'Marcus Sasser', 'via BOS', 1),
    traded(2023, 'IND', 'IND', 'Ben Sheppard', 'from CLE', 1),
    traded(2023, 'CHA', 'CHA', 'Nick Smith Jr.', 'from DEN via NYK/OKC', 1),
    traded(2023, 'UTA', 'UTA', 'Brice Sensabaugh', 'from PHI via BKN', 1),
    traded(2023, 'IND', 'DEN', 'Julian Strawther', 'from BOS', 1),
    traded(2023, 'LAC', 'LAC', 'Kobe Brown', 'from MIL via HOU', 1),

    // --- 2023 Round 2 ---
    traded(2023, 'DET', 'CHA', 'James Nnaji', 'via BOS', 2),
    traded(2023, 'IND', 'DEN', 'Jalen Pickett', 'from HOU', 2),
    traded(2023, 'SAS', 'MIN', 'Leonard Miller', 'Traded to MIN', 2),
    traded(2023, 'CHA', 'SAC', 'Colby Jones', 'from CHA via PHI/ATL', 2),
    traded(2023, 'BOS', 'CHI', 'Julian Phillips', 'from POR via ATL/LAC/DET/CLE', 2),
    traded(2023, 'ORL', 'MIL', 'Andre Jackson Jr.', 'Traded to MIL', 2),
    traded(2023, 'OKC', 'DEN', 'Hunter Tyson', 'from WAS via NOP', 2),
    traded(2023, 'SAC', 'BOS', 'Jordan Walsh', 'from IND', 2),
    traded(2023, 'CHA', 'ATL', 'Mouhamed Gueye', 'from UTA via NYK', 2),
    traded(2023, 'DEN', 'LAL', 'Maxwell Lewis', 'from DAL via OKC', 2),
    traded(2023, 'CHA', 'CHA', 'Amari Bailey', 'from OKC via NYK/BOS', 2),
    traded(2023, 'WAS', 'WAS', 'Tristan Vukčević', 'from CHI via LAL', 2),
    traded(2023, 'POR', 'POR', 'Rayan Rupert', 'from ATL', 2),
    traded(2023, 'SAS', 'SAS', 'Sidy Cissoko', 'from TOR', 2),
    traded(2023, 'MEM', 'MEM', 'GG Jackson', 'from MIN', 2),
    traded(2023, 'ATL', 'ATL', 'Seth Lundy', 'from NOP', 2),
    traded(2023, 'LAL', 'IND', 'Mojave King', 'Traded to IND', 2),
    own(2023, 'LAC', 'Jordan Miller', 2),
    traded(2023, 'CLE', 'CLE', 'Emoni Bates', 'from GSW via UTA/NOP', 2),
    traded(2023, 'OKC', 'OKC', 'Keyontae Johnson', 'from MIA via BOS/MEM/DAL', 2),
    own(2023, 'BKN', 'Jalen Wilson', 2),
    own(2023, 'PHX', 'Toumani Camara', 2),
    traded(2023, 'MIN', 'MIN', 'Jaylen Clark', 'from NYK via CHA', 2),
    own(2023, 'SAC', 'Jalen Slawson', 2),
    traded(2023, 'IND', 'IND', 'Isaiah Wong', 'from CLE via MIL/DET', 2),
    own(2023, 'MEM', 'Tarik Biberović', 2),
    traded(2023, 'WAS', 'GSW', 'Trayce Jackson-Davis', 'from BOS via CHA', 2),
    own(2023, 'MIL', 'Chris Livingston', 2),

    // --- 2022 Round 1 ---
    own(2022, 'ORL', 'Paolo Banchero', 1),
    own(2022, 'OKC', 'Chet Holmgren', 1),
    own(2022, 'HOU', 'Jabari Smith Jr.', 1),
    own(2022, 'SAC', 'Keegan Murray', 1),
    own(2022, 'DET', 'Jaden Ivey', 1),
    own(2022, 'IND', 'Bennedict Mathurin', 1),
    own(2022, 'POR', 'Shaedon Sharpe', 1),
    traded(2022, 'NOP', 'NOP', 'Dyson Daniels', 'from LAL', 1),
    own(2022, 'SAS', 'Jeremy Sochan', 1),
    own(2022, 'WAS', 'Johnny Davis', 1),
    traded(2022, 'NYK', 'OKC', 'Ousmane Dieng', 'Traded to OKC', 1),
    traded(2022, 'OKC', 'OKC', 'Jalen Williams', 'from LAC', 1),
    traded(2022, 'CHA', 'DET', 'Jalen Duren', 'Traded to DET via NYK', 1),
    own(2022, 'CLE', 'Ochai Agbaji', 1),
    traded(2022, 'CHA', 'CHA', 'Mark Williams', 'from NOP', 1),
    own(2022, 'ATL', 'AJ Griffin', 1),
    traded(2022, 'HOU', 'HOU', 'Tari Eason', 'from BKN', 1),
    own(2022, 'CHI', 'Dalen Terry', 1),
    traded(2022, 'MIN', 'MEM', 'Jake LaRavia', 'Traded to MEM', 1),
    traded(2022, 'SAS', 'SAS', 'Malaki Branham', 'from TOR', 1),
    own(2022, 'DEN', 'Christian Braun', 1),
    traded(2022, 'MEM', 'UTA', 'Walker Kessler', 'from UTA', 1),
    traded(2022, 'PHI', 'MEM', 'David Roddy', 'Traded to MEM', 1),
    traded(2022, 'MIL', 'MIL', 'MarJon Beauchamp', 'from MIL via CLE/HOU', 1),
    traded(2022, 'SAS', 'SAS', 'Blake Wesley', 'from BOS', 1),
    traded(2022, 'DAL', 'MIN', 'Wendell Moore Jr.', 'Traded to MIN', 1),
    own(2022, 'MIA', 'Nikola Jović', 1),
    own(2022, 'GSW', 'Patrick Baldwin Jr.', 1),
    traded(2022, 'MEM', 'HOU', 'TyTy Washington Jr.', 'Traded to HOU', 1),
    traded(2022, 'OKC', 'DEN', 'Peyton Watson', 'from PHX', 1),

    // --- 2022 Round 2 ---
    traded(2022, 'IND', 'IND', 'Andrew Nembhard', 'from HOU via CLE', 2),
    own(2022, 'ORL', 'Caleb Houstan', 2),
    traded(2022, 'TOR', 'TOR', 'Christian Koloko', 'from DET via CHI/WAS/SAS', 2),
    own(2022, 'OKC', 'Jaylin Williams', 2),
    traded(2022, 'LAL', 'LAL', 'Max Christie', 'from IND via MIL/ORL', 2),
    traded(2022, 'POR', 'DET', 'Gabriele Procida', 'Traded to DET', 2),
    traded(2022, 'SAC', 'DAL', 'Jaden Hardy', 'Traded to DAL', 2),
    traded(2022, 'SAS', 'MEM', 'Kennedy Chandler', 'from LAL via WAS/CHI', 2),
    traded(2022, 'CLE', 'CLE', 'Khalifa Diop', 'from SAS via UTA', 2),
    traded(2022, 'MIN', 'CHA', 'Bryce McGowens', 'from WAS via CLE', 2),
    own(2022, 'NOP', 'E. J. Liddell', 2),
    own(2022, 'NYK', 'Trevor Keels', 2),
    own(2022, 'LAC', 'Moussa Diabaté', 2),
    traded(2022, 'ATL', 'GSW', 'Ryan Rollins', 'Traded to GSW', 2),
    traded(2022, 'CHA', 'MIN', 'Josh Minott', 'Traded to MIN', 2),
    traded(2022, 'DET', 'DEN', 'Ismaël Kamagate', 'from BKN', 2),
    traded(2022, 'MEM', 'MEM', 'Vince Williams Jr.', 'from CLE via ATL/NOP', 2),
    traded(2022, 'MIN', 'IND', 'Kendall Brown', 'Traded to IND', 2),
    traded(2022, 'CLE', 'CLE', 'Isaiah Mobley', 'from CHI via DET/MEM/SAC', 2),
    traded(2022, 'MIN', 'MIN', 'Matteo Spagnolo', 'from DEN via PHI', 2),
    traded(2022, 'GSW', 'ATL', 'Tyrese Martin', 'from TOR via PHI', 2),
    traded(2022, 'NOP', 'NOP', 'Karlo Matković', 'from UTA', 2),
    own(2022, 'BOS', 'JD Davison', 2),
    traded(2022, 'WAS', 'WAS', 'Yannick Nzosa', 'from DAL', 2),
    own(2022, 'GSW', 'Gui Santos', 2),
    traded(2022, 'CLE', 'CLE', 'Luke Travers', 'from MIA via IND', 2),
    traded(2022, 'POR', 'POR', 'Jabari Walker', 'from MEM via UTA', 2),
    traded(2022, 'IND', 'MIL', 'Hugo Besson', 'from PHX', 2),
];
